Acara/urls.py
from django.urls import path
from sepeda import views
app_name = 'Acara'

urlpatterns = [
	path('', views.listacara, name = 'acara')
]

bikesharing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include(('firstpage.urls', 'firstpage'), namespace="firstpage")),
  path('sepeda/', include('sepeda.urls')),
  path('stasiun/', include('stasiun.urls')),
  path('voucher/', include('voucher.urls')),
  path('peminjaman/', include('peminjaman.urls')),
  path('Penugasan/', include('Penugasan.urls')),
  path('Acara/', include('Acara.urls'))
   
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

firstpage/urls.py
from django.urls import path
from firstpage import views

urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up', views.signup, name='sign-up'),
    path('login', views.login, name='login'),
    path('arahinkesini', views.arahinkesini, name='ea'),
    path('logout', views.logout, name='logout'),
]

firstpage/models.py
from django.db import models

# Create your models here.

firstpage/views.py
from django.shortcuts import render, redirect
from django.db import connection

# Create your views here.
cursor = connection.cursor()
def index(request):
	if 'ktp' in request.session:
		return render(request, 'dashboard.html', {'role':request.session['role']})
	else:
		return render(request,'login-register.html')

def signup(request):
	if request.method == "GET":
		return render(request,'signup.html')
	elif request.method == "POST":
		print(request.POST["role"])


def login(request):

	return render(request,'login.html')

def logout(request):
	del request.session['ktp']
	return redirect('/')

def arahinkesini(request):
	ktp = request.POST["ktp"]
	email = request.POST["email"]

	ketemu = False
	cursor.execute("SELECT * FROM ANGGOTA NATURAL JOIN PERSON WHERE ktp='" + ktp +  "' and email='"+email+"'")
	hasil = dictfetchall(cursor)
	if len(hasil) > 0:
		role = 'anggota'
		ketemu = True

	else:
		cursor.execute("SELECT * FROM PETUGAS NATURAL JOIN PERSON WHERE ktp='" + ktp +  "' and email='"+email+"'")
		hasil = dictfetchall(cursor)
		if len(hasil) > 0:
			role = 'petugas'
			ketemu = True
		else:
			cursor.execute("SELECT * FROM PERSON WHERE ktp='" + ktp +  "' and email='"+email+"'")
			hasil = dictfetchall(cursor)
			if len(hasil) > 0:
				role = 'admin'
				ketemu = True

	if ketemu:
		request.session['ktp'] = ktp
		request.session['role'] = role
		return redirect('/')
	else:
		return redirect('/login')

def dictfetchall(cursor): 
	"Returns all rows from a cursor as a dict" 
	desc = cursor.description 
	return [
			dict(zip([col[0] for col in desc], row)) 
			for row in cursor.fetchall() 
	]

firstpage/templates/dashboard.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.1.3.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-circle-o"></i>
        <b> BIKE SHARING</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar11" style="">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar11">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <font color="white"> Informasi Saldo: <br> [SALDO] </font>
          </li>
          <li class="nav-item"> <a class="nav-link" href="#">Daftar Stasiun</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">Daftar Sepeda</a> </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Peminjaman</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Buat Peminjaman</a>
              <a class="dropdown-item" href="#">Daftar Peminjaman</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Transaksi</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Topup Sharebike Pay</a>
              <a class="dropdown-item" href="#">Riwayat Transaksi</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="#">Daftar Acara</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">Daftar Voucher</a> </li>
        </ul> <a href="{% url 'firstpage:logout' %}" class="btn btn-primary navbar-btn ml-md-2">Logout</a>
      </div>
    </div>
  </nav>
  <p> saya {{role}} </p>
</body>

firstpage/templates/login-register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!--
  <link rel="stylesheet" href="theme.css" type="text/css">
  -->
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
</head>

<body>
  <div class="py-5 text-center align-items-center d-flex" style="background-image: linear-gradient(to left bottom, rgba(189, 195, 199, 0.75), rgba(44, 62, 80, 0.75)); background-size: 100%;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-8 mx-auto"> <i class="d-block fa fa-stop-circle mb-3 text-muted fa-5x"></i>
          <h1 class="display-3 mb-4">Bike Sharing</h1>
          <!-- localhost perlu diganti lagi-->
          <a class="btn btn-lg mx-1 btn-outline-dark" href="{% url 'firstpage:sign-up' %}" draggable="true">Register</a> 
          <a href="{% url 'firstpage:login' %}" class="btn btn-lg btn-outline-dark">Login</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
  </div>
  <div class="py-5">
    <div class="container">
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>
</body>

</html>

firstpage/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.1.3.css">
</head>

<body>
  <div class="py-5 text-center" style="background-image: url('https://static.pingendo.com/cover-bubble-dark.svg');background-size:cover;">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-md-6 col-10 bg- p-5">
          <h1 class="mb-4">Log in</h1>
          <form action="{% url 'firstpage:ea' %}", method="POST">
          	{% csrf_token %}
            <div class="form-group mb-3"> <input type="text" class="form-control" placeholder="Nomor KTP" id="form9" name="ktp"> </div>
            <div class="form-group"> <input type="email" class="form-control" placeholder="Enter email" id="form10" name="email"> </div>
            <button type="submit" class="btn btn-lg mx-1 btn-outline-dark">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>
</body>

</html>

firstpage/templates/signup.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.1.3.css">

</head>

<body>
  <div class="py-5 text-center">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-lg-6 col-10">
          <h1>Bike Sharing</h1>
          <form class="text-left" action="{% url 'firstpage:sign-up' %}" method="POST">
            {% csrf_token %}
            <div class="dropdown">
              <label for="form15">Role</label>
              <br>
               <div class="dropdown-dark">
                <select name="role" class="dropdown-select">
                  <option value="">Select…</option>
                  <option value="1">Admin</option>
                  <option value="2">Anggota</option>
                  <option value="3">Petugas</option>
                </select>
            </div>
            <div class="form-group"> <label for="form16">Nomor KTP</label> <input type="text" class="form-control" id="form16"> </div>
            <div class="form-group"> <label for="form17">Nama Lengkap</label> <input type="text" class="form-control" id="form17"> </div>
            <div class="form-group"> <label for="form18">Email</label> <input type="email" class="form-control" id="form18"> </div>
            <div class="form-group"> <label for="form18">Tanggal lahir</label> <input type="date" class="form-control" id="form18"> </div>
            <div class="form-group"> <label for="form17">Nomor Telpon</label> <input type="text" class="form-control" id="form17"> </div>
            <div class="form-group"> <label for="form17">Alamat</label> <input type="text" class="form-control" id="form17"> </div>
            <div class="form-row">
            </div> <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>

  <script>
function myFunction() {
  var x = document.getElementById("dropdown").name;
  document.getElementById("demo").innerHTML = x;
}
</script>

</body>

</html>