Acara/urls.py
from django.urls import path
from sepeda import views
app_name = 'Acara'

urlpatterns = [
	path('', views.listacara, name = 'acara')
]

bikesharing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include(('firstpage.urls', 'firstpage'), namespace="firstpage")),
  path('sepeda/', include('sepeda.urls')),
  path('stasiun/', include('stasiun.urls')),
  path('voucher/', include('voucher.urls')),
  path('peminjaman/', include('peminjaman.urls')),
  path('Penugasan/', include('Penugasan.urls')),
  path('Acara/', include('Acara.urls'))
   
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sepeda/urls.py
from django.urls import path
from sepeda import views
app_name = 'sepeda'

urlpatterns = [
	path('', views.listsepeda, name = 'sepeda'),
	path('/createsepeda',views.sepeda,name='createsepeda'),
	path('/updatesepeda',views.updatesepeda,name='updatesepeda'),
	path('/postsepeda',views.postsepeda, name = 'postsepeda'),
    path('/deletesepeda',views.deletesepeda, name = 'deletesepeda'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
	path('/sortSepedaDESC/',views.sortSepedaDESC, name = 'sortSepedaDESC'),
	path('/sortSepedaASC/', views.sortSepedaASC, name = 'sortSepedaASC'),
]

sepeda/models.py
from django.db import models

# Create your models here.
class Stasiun(models.Model):
    nama = models.CharField(primary_key=True, max_length=50)
    alamat = models.CharField(max_length=300)
    latitude = models.IntegerField(blank=True, null=True)
    longitude = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'stasiun'

sepeda/forms.py
from django import forms
from .models import Stasiun


class StasiunForm(forms.Form):
    nama = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-field flex-column'}))
    alamat = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'class': 'form-field flex-column'}))
    latitude = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-field flex-column'}), required=False)
    longitude = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-field flex-column'}), required=False)

sepeda/views.py
from django.shortcuts import render
from django.db import connection
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt


def sepeda(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("SELECT nama FROM stasiun")

    result1 = c.fetchall()
    response['stasiun'] = result1
    print(response)
    return render(request, 'createsepeda.html',response)

def postsepeda(request):
    if(request.method=="POST"):
        merk = request.POST['merk']
        jenis = request.POST['jenis']
        status = request.POST['status']
        stasiun = request.POST['stasiun']
        penyumbang = request.POST['penyumbang']

        print(status)
        statusNow = False
        if(str(status)=='Tersedia'):
            statusNow = True
        else:
            statusNow = False

        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')
        c.execute("select a.no_kartu from anggota as a, person as p where p.nama='"+penyumbang+"' and p.ktp = a.ktp;")
        result = c.fetchone()
        no_kartu_penyumbang = result[0]

        c.execute("select id_stasiun from stasiun where nama='"+stasiun+"';")
        result1 = c.fetchone()
        id_stasiun = result1[0]

        c.execute("select nomor from sepeda order by cast (nomor as int) desc;")
        result2 = c.fetchone()
        nomor = int(result2[0]) +1

        c.execute("INSERT INTO sepeda(nomor,merk,jenis,status,id_stasiun,no_kartu_penyumbang) values("+"'"+str(nomor)+"','" +str(merk)+"','" + str(jenis) +"','" + str(statusNow) +"', '" + str(id_stasiun) +"', '" + str(no_kartu_penyumbang) +"' );")

        return HttpResponseRedirect('/sepeda')

    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda/createsepeda')


def listsepeda(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("select s.nama, p.nama, n.nomor, n.merk, n.jenis, n.status from sepeda as n, stasiun as s, person as p, anggota as a where n.no_kartu_penyumbang = a.no_kartu and a.ktp = p.ktp and n.id_stasiun = s.id_stasiun; ")
    result1 = c.fetchall()
    response['sepeda'] = result1
    print(response)
    return render(request, 'daftar_sepeda.html',response)


def updatesepeda(request):
    return render(request, 'updateSepeda.html')

@csrf_exempt
def detailupdate(request):
    if(request.method=="POST"):
        response={}
        sepeda= request.POST['id']
        c = connection.cursor()
        c.execute('set search_path to bike_station,public')
        c.execute("select * from sepeda where nomor='"+sepeda+"';")
        stasiun = c.fetchone()

        c.execute("select s.nama from stasiun as s, sepeda as a where a.nomor ='"+sepeda+"' and a.id_stasiun = s.id_stasiun;")
        nama_stasiun = c.fetchone()

        c.execute("select p.nama from person as p, anggota as a, sepeda as n where n.nomor='"+sepeda+"' and a.no_kartu=n.no_kartu_penyumbang and p.ktp=a.ktp;")
        result = c.fetchone()
        nama_penyumbang = result[0]

        c.execute("select jenis from sepeda where nomor='"+sepeda+"';")
        jenis = c.fetchone()

        c.execute("select status from sepeda where nomor='"+sepeda+"';")
        status = c.fetchone()

        c.execute("select merk from sepeda where nomor='"+sepeda+"';")
        merk = c.fetchone()

        c.execute("select p.nama from person as p, anggota as a where a.ktp=p.ktp")
        penyumbang = c.fetchall()

        c.execute("select nama from stasiun")
        stasiun = c.fetchall()
        response['stasiun'] = stasiun
        response['penyumbang'] = penyumbang
        response['sepeda'] = sepeda
        response['nama_stasiun'] = nama_stasiun
        response['nama_penyumbang'] = nama_penyumbang
        response['jenis'] = jenis[0]
        response['merk'] = merk[0]
        response['status'] = status[0]

        return JsonResponse(response)

    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda/updatesepeda')

@csrf_exempt
def deletesepeda(request):
    if(request.method=="POST"):
        nomor= request.POST['id']
        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')
        c.execute("delete from sepeda where nomor='"+nomor+"';")

        return HttpResponseRedirect('/peminjaman')
    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/peminjaman')

def sortSepedaASC(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("select * from sepeda order by merk ASC")
    result1 = c.fetchall()
    response['sepeda'] = result1
    print(response)
    return render(request, 'daftar_sepeda.html',response)

def sortSepedaDESC(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("select * from sepeda order by merk DESC")
    result1 = c.fetchall()
    response['sepeda'] = result1
    print(response)
    return render(request, 'daftar_sepeda.html',response)

sepeda/templates/createSepeda.html
{% extends 'navbar.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>


{% endblock %}

{% block body %}

<section class="add">
  <div class="container-edit">
      <div class="add-content">
        {% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}
        <div class="row">
          <div class="col-md-6">
            <div class="add-form">
                <h2 class="form-title1">Penambahan Sepeda</h2>
                <form action="/sepeda/postsepeda" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="merk"><i class="name"></i></label>
                      <input type="text" name="merk" id="name" placeholder="Merk" required />
                  </div>
                  <div class="form-group">
                      <label for="jenis"><i class="name"></i></label>
                      <input type="text" name="jenis" id="name" placeholder="Jenis" required />
                  </div>
                  <div class="form-group">
                      <label for="status"><i class="name"></i></label>
                      <input type="text" name="status" id="name" placeholder="Status" required />
                  </div>
                  <div class="form-group">
                      <label for="stasiun"><i class="name"></i></label>
                      <input type="text" name="stasiun" id="name" placeholder="Stasiun" required />
                  </div>
                  <div class="form-group">
                      <label for="penyumbang"><i class="name"></i></label>
                      <input type="text" name="penyumbang" id="name" placeholder="Penyumbang" />
                  </div>
                  <div class="form-group form-button">
                      <input type="submit" name="add" id="add" class="form-submit" value="Submit"/>
                  </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

sepeda/templates/daftar_sepeda.html
{% extends 'navbar.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<style>
  .dropbtn {
    background-color: #3498DB;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
  }

  .dropbtn:hover, .dropbtn:focus {
    background-color: #2980B9;
  }

  .dropdown {
    position: relative;
    display: inline-block;
    text-align:center;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    overflow: auto;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  .dropdown a:hover {background-color: #ddd;}

  .show {display: block;}
</style>
{% endblock %}

{% block body %}

<div class="container-daftar">
    <div class="add-content">
      <div class="row">
            <h2 class="form-title1">Daftar Sepeda</h2>
            <div class="container-sorting">
              <div class="row">
                <div class="dropdown" style="position: relative; left: -190px; top: 50px; width: 240px; height:30px;>
                    <button onclick="myFunction()" type="button" class="btn btn-primary btn-xs dropdown-toggle">Sorting</button>
                    <div id="myDropdown" class="dropdown-content">
                      <a href="{% url "stasiun:sortStasiunASC" %}">ASC</a>
                      <a href="{% url "stasiun:sortStasiunDESC" %}">DESC</a>
                    </div>
                </div>
              </div>
            </div>
            {% if request.session.role == "petugas" %}
            <div class="table-responsive">
            <table id="mytable" class="table table-bordred table-striped">

               <thead>
                  <th style="text-align: center;">Nomor</th>
                  <th style="text-align: center;">Merk</th>
                  <th style="text-align: center;">Jenis</th>
                  <th style="text-align: center;">Stasiun</th>
                  <th style="text-align: center;">Status</th>
                  <th style="text-align: center;">Penyumbang</th>
                  <th style="text-align: center;">Action</th>
               </thead>
              <tbody>
               {% for i in sepeda %}
                    <tr>
                    <td>{{i.2}}</td>
                    <td>{{i.3}}</td>
                    <td>{{i.4}}</td>
                    <td>{{i.5}}</td>
                    <td>{{i.0}}</td>
                    <td>{{i.1}}</td>
                    <td><a data-placement="top" data-toggle="tooltip" href="{% url 'sepeda:updatesepeda' %}" title="Update"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >Update</button></a>
                        <a data-placement="top" data-toggle="tooltip" title="Delete"><a href="url_to_delete" class="btn btn-danger btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"  onclick="return confirm('Are you sure you want to delete this item?');">Delete</a></td>
                {% endfor %}
                </tbody>

            </table>
          {% elif request.session.role == "anggota" %}
          <table id="mytable" class="table table-bordred table-striped">

             <thead>
                <th style="text-align: center;">Nomor</th>
                <th style="text-align: center;">Merk</th>
                <th style="text-align: center;">Jenis</th>
                <th style="text-align: center;">Stasiun</th>
                <th style="text-align: center;">Status</th>
                <th style="text-align: center;">Penyumbang</th>
                <th style="text-align: center;">Action</th>
             </thead>
            <tbody>
             {% for i in sepeda %}
                  <tr>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td>{{i.4}}</td>
                  <td>{{i.5}}</td>
                  <td>{{i.0}}</td>
                  <td>{{i.1}}</td>
                  <td><a data-placement="top" data-toggle="tooltip" title="Pinjam"><button class="btn btn-primary btn-xs" href="{% url "sepeda:sepeda" %}">Pinjam</button></a></td>
                  </tr>
              </tbody>
              {% endfor %}
          </table>
          {% endif %}
          </div>
      </div>
  </div>
</div>

<script>
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    }


    $(document).ready( function () {
        $('#mytable').DataTable();
    } );

    </script>
{% endblock %}

sepeda/templates/updateSepeda.html
{% extends 'navbar.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>


{% endblock %}

{% block body %}

<section class="update">
    <div class="container-edit">
        <div class="update-content">
          <div class="row">
            <div class="col-md-6">
              <div class="update-form">
                  <h2 class="form-title">Update Sepeda</h2>
                  <form action="/sepeda/postsepeda" method="POST">
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Merk" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Jenis" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Status" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Stasiun" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Penyumbang" />
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="update" id="update" class="form-submit" value="Update"/>
                    </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
    </div>
</section>
{% endblock %}